xingyunbe/xingyun/urls.py
'''
Created on Mar 17, 2013

@author: mingqi
'''
from .views import *
from .models import *
from django.conf.urls import patterns, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.decorators.http import require_GET, require_POST
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.decorators.gzip  import gzip_page


urlpatterns = patterns('',
    url(r'^$', ActivityList.as_view()),
    
    url(r'^login/?$', csrf_exempt(LoginView.as_view()), name='login'),
    url(r'^logout/?$', logout_view , name='logout'),
    url(r'^changepassword/?$', ChangePasswordView.as_view() , name='changepassword'),
    url(r'^changepassword_succesful/?$', change_password_succesful , name='change_password_succesful'),
    
    ### menu url ###
    url(r'^menu/list/?$', login_required(MenuItemList.as_view(),login_url=reverse_lazy('login')), name='menu/list'),
    #url(r'^menu/list/?$', MenuItemList.as_view(), name='menu/list'),
    url(r'^menu/add/?$', login_required(MenuItemCreate.as_view(),login_url=reverse_lazy('login')), name='menu/add'),
    url(r'^menu/(?P<pk>\w+)/update/?$', login_required(MenuItemUpdate.as_view(),login_url=reverse_lazy('login')), name='menu/update'),
    url(r'^menu/(?P<pk>\w+)/delete/?$', login_required(ObjectDeleteView.as_view(model=MenuItem, succesful_view='menu/list'),
                                                       login_url=reverse_lazy('login')), name='menu/delete'),
    
    ### order url ###
    url(r'^order/list/?$', login_required(OrderList.as_view(),login_url=reverse_lazy('login')), name='order/list'),
    url(r'^order/(?P<pk>\w+)/update/?$', login_required(OrderUpdate.as_view(),login_url=reverse_lazy('login')), name='order/update'),
    url(r'^order/(?P<pk>\w+)/delete/?$', login_required(ObjectDeleteView.as_view(model=Order, succesful_view='order/list'),
                                                        login_url=reverse_lazy('login')), name='order/delete'),
    
    ### activity url ###
    url(r'^activity/list/?$', login_required(ActivityList.as_view(),login_url=reverse_lazy('login')), name='activity/list'),
    url(r'^activity/add/?$', login_required(ActivityCreate.as_view(),login_url=reverse_lazy('login')), name='activity/add'),
    url(r'^activity/(?P<pk>\w+)/update/?$', login_required(ActivityUpdate.as_view(),login_url=reverse_lazy('login')), name='activity/update'),
    url(r'^activity/(?P<pk>\w+)/delete/?$', login_required(ObjectDeleteView.as_view(model=Activity, succesful_view='activity/list'),
                                                           login_url=reverse_lazy('login')), name='activity/delete'),
    
    ### customer urls ###
    url(r'^customer/list/?$', login_required(CustomerList.as_view(),login_url=reverse_lazy('login')), name='customer/list'),
    url(r'^customer/(?P<pk>\w+)/resetpassword/?$', login_required(CustomerPasswordReset.as_view(),
                                                                  login_url=reverse_lazy('login')), name='customer/resetpassword'),
    
    
    # api url    
    url(r'^api/menus/?$', delay(APIMenusView.as_view()), name='api/menus'),
    url(r'^api/orders/?$', csrf_exempt(delay(APIOrdersView.as_view())), name='api/orders'),
    url(r'^api/order/(?P<pk>\w+)/?$', csrf_exempt(delay(APIOrderView.as_view())), name='api/order'),
    url(r'^api/activities/?$', delay(APIActivitiesView.as_view()), name='api/activities'),
    url(r'^api/customer/signin?$', delay(APICustomerSigninView.as_view())),
    url(r'^api/customer/signup?$', csrf_exempt(delay(APICustomerSignupView.as_view()))),
    url(r'^api/customer/(?P<pk>\w+)/?$', csrf_exempt(delay(APICustomerView.as_view())), name='api/order'),
)


urlpatterns += staticfiles_urlpatterns()

xingyunbe/xingyunbe/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^xingyun/', include('xingyun.urls')),
)

xingyunbe/xingyun/models.py
#-*- coding: utf-8 -*-
'''
Created on Mar 17, 2013

@author: mingqi
'''

from django.db import models
from django import forms
from django.template.defaultfilters import filesizeformat
from datetime import datetime

def model_to_jsondict(model):
    d = dict()
    for field in model._meta.fields:
        value = getattr(model, field.name)
        if isinstance(field, models.IntegerField):
            d[field.name] = int(value)
        elif isinstance(field, models.DecimalField):
            d[field.name] = int(value)
        else:
            d[field.name] = value
    return d

class ModelAsDictMixin(object):
    def as_dict(self, **kwargs ):
        """
        transform Model to a dict
        kwargs: 
            one2many_fields: to override default one2many_fields
        """
        d = dict()
        for field in self._meta.fields:
            value = getattr(self, field.name)
            if value:
                if isinstance(field, models.IntegerField):
                    d[field.name] = int(value)
                elif isinstance(field, models.DecimalField):
                    d[field.name] = int(value)
                elif isinstance(field, models.ForeignKey):
                    pass
                else:
                    d[field.name] = value
        
        one2many_fields = None
        
        if hasattr(self, 'one2many_fields'):
            one2many_fields = getattr(self, 'one2many_fields')
        
        if 'one2many_fields' in kwargs:
            one2many_fields = kwargs['one2many_fields']
        
        if one2many_fields:
            for one2many_field in one2many_fields:
                d[one2many_field] = [x.as_dict() for x in getattr(self, one2many_field).all()]
        return d
    
class ModelSetFieldsByDictMixin(object):
    
    def set_fields_by_dict(self, d):
        for key, value in d.items():
            if hasattr(self, key):
                setattr(self, key, value)
    


class ContentTypeRestrictedFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        self.content_types = kwargs.pop("content_types")
        self.max_upload_size = kwargs.pop("max_upload_size")
        super(ContentTypeRestrictedFileField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):        
        data = super(ContentTypeRestrictedFileField, self).clean(*args, **kwargs)
        file = data
        try:
            content_type = file.content_type
            if content_type in self.content_types:
                if file._size > self.max_upload_size:
                    raise forms.ValidationError(u'文件不能大于%s. 您上传的文件是%s' % (filesizeformat(self.max_upload_size), filesizeformat(file._size)))
            else:
                raise forms.ValidationError(u'上传的图片类型不匹配,只支持jpg,gif和png的格式图片')
        except AttributeError:
            pass        
    
        return data

class Sequence(models.Model):
    sequenceName = models.CharField(max_length=20, primary_key = True, db_column = 'sequence_name')
    sequenceValue = models.IntegerField(db_column='sequence_value')
    
    class Meta:
        db_table = 'sequence'
   
def next_sequence(sequenceName): 
    try:
        seq = Sequence.objects.get(sequenceName=sequenceName)
    except Sequence.DoesNotExist:
        seq = Sequence()
        seq.sequenceName = sequenceName
        seq.sequenceValue = 1
    value = seq.sequenceValue
    seq.sequenceValue = seq.sequenceValue + 1
    seq.save()
    return value

############# Menu Models #################
class MenuItem(models.Model, ModelAsDictMixin):
    MENU_ITEM_CATEGORY_CHOICES = (
        (1, '正餐'),
        (2, '沙拉'),
        (3, '其他'),
    )
    menu_item_id = models.IntegerField(primary_key = True)
    title = models.CharField('菜品名', max_length=50)
    price = models.DecimalField('价格', max_digits=7, decimal_places=2)
    category = models.IntegerField('类别', choices=MENU_ITEM_CATEGORY_CHOICES)
    sorted_seq = models.IntegerField('展示序号' )
    image_uri = models.CharField(max_length=255)
    
    class Meta:
        db_table = 'menu_items'
        
    
class MenuItemForm(forms.ModelForm): 
    image_file = ContentTypeRestrictedFileField(label='图片(400x400)', content_types=['image/gif', 'image/jpeg', 'image/pjpeg', 'image/png'], max_upload_size = 1024 * 50000)
    class Meta:
        model = MenuItem
        fields = ('image_file', 'title', 'price', 'category', 'sorted_seq')
        
class MenuItemUpdateForm(forms.ModelForm):
    image_file = ContentTypeRestrictedFileField(label='图片(400x400)', 
                                               content_types=['image/gif', 'image/jpeg', 'image/pjpeg', 'image/png'], 
                                               max_upload_size = 1024 * 50000, required=False)
    menu_item_id = forms.CharField(widget=forms.HiddenInput)
    class Meta:
        model = MenuItem
        fields = ('image_file', 'title', 'price', 'category', 'sorted_seq', 'menu_item_id')
        
############# Order Models #################
class Order(models.Model, ModelAsDictMixin, ModelSetFieldsByDictMixin):
    ORDER_STATUS_CHOICES = (
        (1, '未处理'),
        (2, '预定成功'),
        (3, '取消'),
    )
    BOX_REQUIRED_CHOICES = (
        (True, '是'),
        (False, '否'),
    )
    
    order_id = models.IntegerField(primary_key = True)
    customer_id = models.IntegerField()
    contact_name = models.CharField('顾客姓名',max_length=50)
    contact_phone = models.CharField('联系电话', max_length=50)
    people_number = models.IntegerField('用餐人数')
    box_required = models.BooleanField('是否包厢', choices=BOX_REQUIRED_CHOICES)
    order_price = models.DecimalField('订单总价', max_digits=7, decimal_places=2)
    dishes_count = models.IntegerField('菜品数量', db_column='dish_count')
    reserved_time = models.DateTimeField('就餐时间')
    order_creation_time = models.DateTimeField('下单时间')
    order_status = models.IntegerField('订单状态', choices=ORDER_STATUS_CHOICES)
    other_requirements = models.TextField('其他要求')
    
    one2many_fields = ('dishes',)
    class Meta:
        db_table = 'customer_orders'
        
class OrderForm(forms.ModelForm): 
    order_id = forms.IntegerField(widget=forms.HiddenInput)
    customer_id = forms.IntegerField(widget=forms.HiddenInput)
    
    reserved_time =       forms.DateTimeField(label='就餐时间', input_formats=('%Y-%m-%d %H:%M',), widget=forms.DateTimeInput(attrs={'readonly': 'readonly'}, format='%Y-%m-%d %H:%M'))
    order_creation_time = forms.DateTimeField(label='下单时间', input_formats=('%Y-%m-%d %H:%M',), widget=forms.DateTimeInput(attrs={'readonly': 'readonly'}, format='%Y-%m-%d %H:%M'))
    
    class Meta:
        model = Order
        widgets = {
            'order_price' : forms.TextInput(attrs={'readonly': 'readonly'}),
            'dishes_count' : forms.TextInput(attrs={'readonly': 'readonly'}),
        }
        
class OrderDish(models.Model, ModelAsDictMixin): 
    order = models.ForeignKey(Order, related_name='dishes')
    order_dish_id = models.IntegerField(primary_key = True)
    title = models.CharField('菜品名', max_length=50)
    price = models.DecimalField('价格', max_digits=7, decimal_places=2)
    quantity = models.IntegerField('数量', db_column = 'quantity')
    image_uri = models.CharField(max_length=255)
    
    class Meta:
        db_table = 'customer_order_dishes'
        
class Activity(models.Model, ModelAsDictMixin):
    activity_id = models.IntegerField(primary_key = True)
    image_uri = models.CharField(max_length = 100)
    sorted_seq = models.IntegerField('显示序号')
    
    class Meta:
        db_table = 'activities'
        
class ActivityForm(forms.ModelForm): 
    image_file = ContentTypeRestrictedFileField(label='图片', content_types=['image/gif', 'image/jpeg', 'image/pjpeg', 'image/png'], max_upload_size = 1024 * 500)
    class Meta:
        model = Activity
        fields = ('image_file', 'sorted_seq')
        
class ActivityUpdateForm(forms.ModelForm): 
    image_file = ContentTypeRestrictedFileField(label='图片', content_types=['image/gif', 'image/jpeg', 'image/pjpeg', 'image/png'], max_upload_size = 1024 * 500, required=False)
    activity_id = forms.CharField(widget=forms.HiddenInput)
    class Meta:
        model = Activity
        fields = ('image_file', 'sorted_seq', 'activity_id')
       
class Customer(models.Model, ModelSetFieldsByDictMixin, ModelAsDictMixin): 
    customer_id = models.IntegerField(primary_key = True)
    name = models.CharField(max_length = 20, unique = True)
    password = models.CharField(max_length = 20)
    contact_name = models.CharField(max_length = 20, blank = True)
    contact_phone = models.CharField(max_length = 20, blank = True)
    
    class Meta:
        db_table = 'customers'
        
class CustomerResetPasswordForm(forms.ModelForm):
    customer_id = forms.CharField(widget=forms.HiddenInput)
    name = forms.CharField(label = '用户名', widget=forms.TextInput(attrs={'readonly':'readonly'}))
    password = forms.CharField(label='密码', initial='', required=True, widget=forms.PasswordInput())
    repassword = forms.CharField(label='再输一遍', initial='', required=True, widget=forms.PasswordInput())
    
    def clean(self):
        form_data = self.cleaned_data
        
        if 'password' in form_data or 'repassword' in form_data:
            if form_data['password'] != form_data['repassword']:
                self._errors["repassword"] = "两次输入的密码不匹配"
                del form_data['password']
        return form_data
    
    class Meta:
        model = Customer
        fields = ('customer_id', 'name','password','repassword')
        
class LoginForm(forms.Form):
    user = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20)
    
class ChangePasswordForm(forms.Form):
    password = forms.CharField(label='新密码', initial='', required=True, widget=forms.PasswordInput())
    repassword = forms.CharField(label='再输一遍', initial='', required=True, widget=forms.PasswordInput())
    
    def clean(self):
        form_data = self.cleaned_data
        

xingyunbe/xingyun/templates/activity_add.html
{% extends "layout.html" %}

{% block nav_activity_class %}active{%endblock%}

{% block content %}
<div class="span6">
<form class="form-horizontal" method='POST' enctype='multipart/form-data' action="{% url 'activity/add' %}">
	{% csrf_token %}
	{% for field in form.visible_fields %}
	<div class="control-group {% if field.errors %} error {% endif%} ">
		<label class="control-label">{{field.label}}</label>
		<div class="controls">
			{{field}}
			{% if field.errors %}	
			<span class="help-inline">{{field.errors}}</span>
			{%endif%}
		</div>
	</div>
	{% endfor %}
	
	{% for field in form.hidden_fields %}
	{{field}}	
	{% endfor %}
	
<!--  	
	<div class="control-group error">
		<label class="control-label">菜品名</label>
		<div class="controls">
			<input type="text" id="title" name="title"></input>
			<span class="help-inline">{{form.title.errors}}</span>
		</div>
	</div>	
	<div class="control-group">
		<label class="control-label">价格</label>
		<div class="controls">
			<input type="text" id="price" name="price"></input>
		</div>
	</div>	
	
	<div class="control-group">
		<label class="control-label">类别</label>
		<div class="controls">
			<input type="text" id="category" name="category"></input>
		</div>
	</div>	
	
			
	<div class="control-group">
		<label class="control-label">序号</label>
		<div class="controls">
			<input type="text" id="orderSeq" name="orderSeq"></input>
		</div>
	</div>	
-->	
	<div class="control-group">
		<div class="controls">
			<button type="submit" class="btn btn-primary">增加</button>
		</div>
	</div>	
	
</form>
</div>
{% endblock %}

xingyunbe/xingyun/templates/activity_list.html
{% extends "layout.html" %}

{% block nav_activity_class %}active{%endblock%}

{% block content %}
<script type="text/javascript">
$(document).ready(function() {
    $('a[data-confirm]').click(function(ev) {
        var href = $(this).attr('href');

        if (!$('#dataConfirmModal').length) {
            $('body').append('<div id="dataConfirmModal" class="modal" role="dialog" aria-labelledby="dataConfirmLabel" aria-hidden="true"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="dataConfirmLabel">确认删除</h3></div><div class="modal-body"></div><div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button><a class="btn btn-primary" id="dataConfirmOK">OK</a></div></div>');
        } 
        $('#dataConfirmModal').find('.modal-body').text($(this).attr('data-confirm'));
        $('#dataConfirmOK').attr('href', href);
        $('#dataConfirmModal').modal({show:true});
        return false;
    });
});
</script>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary" onclick="javascript:window.location =''">Save changes</button>
  </div>
</div>

	<div class="container span8">
		<a href="{% url 'activity/add' %}"><button class="btn btn-primary" >增加活动</button></a>
		</br>
		</br>

		<table class="table table-striped">
			<tr>
				<th>图片</th>
				<th>显示序号</th>
				<th>操作</th>
			</tr>
			{% for activity in object_list%}
			<tr>
				<td><img src="{{STATIC_URL}}/menu/{{activity.image_uri}}" class="img-roundeds" width="320" heigth="460" /></td>
				<td>{{activity.sorted_seq}}</td>
				<td>
					<div class="btn-group">
					  <a class="btn dropdown-toggle btn-primary" data-toggle="dropdown" href="#">
					   	操作 
					    <span class="caret"></span>
					  </a>
					  <ul class="dropdown-menu">
					  	<li><a href="{%url 'activity/update' activity.activity_id %}">查看/修改</a></li>
						<li><a href="{%url 'activity/delete' activity.activity_id %}" data-confirm="你确定要删除吗?" onclick="javascript:$('.alert').alert()">删除</a></li>
					  </ul>
					</div>				
				</td>
			</tr>
			{% endfor %}
		</table>
	</div>

{% endblock %}

xingyunbe/xingyun/templates/activity_update.html
{% extends "layout.html" %}

{% block nav_activity_class %}active{%endblock%}
{% block content %}
<div class="span6">
<form class="form-horizontal" method='POST' enctype='multipart/form-data' action="{% url 'activity/update' form.activity_id.value %}">
	{% csrf_token %}
	{% for field in form.visible_fields %}
	<div class="control-group {% if field.errors %} error {% endif%} ">
		<label class="control-label">{{field.label}}</label>
		<div class="controls">
			{{field}}
			{% if field.errors %}	
			<span class="help-inline">{{field.errors}}</span>
			{%endif%}
		</div>
	</div>
	{% endfor %}
	
	{% for field in form.hidden_fields %}
	{{field}}	
	{% endfor %}
	
	<div class="control-group">
		<div class="controls">
			<button type="submit" class="btn btn-primary">修改</button>
		</div>
	</div>
	
</form>
</div>
{% endblock %}

xingyunbe/xingyun/templates/change_password_succesful.html
{% extends "layout.html" %}

{% block nav_changepassword_class %}active{%endblock%}
{% block content %}
<div class="span6">
密码修改成功
</div>
{% endblock %}

xingyunbe/xingyun/templates/menu_list.html
{% extends "layout.html" %}

{% block nav_menu_class %}active{%endblock%}

{% block content %}
<script type="text/javascript">
$(document).ready(function() {
    $('a[data-confirm]').click(function(ev) {
        var href = $(this).attr('href');

        if (!$('#dataConfirmModal').length) {
            $('body').append('<div id="dataConfirmModal" class="modal" role="dialog" aria-labelledby="dataConfirmLabel" aria-hidden="true"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="dataConfirmLabel">确认删除</h3></div><div class="modal-body"></div><div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button><a class="btn btn-primary" id="dataConfirmOK">OK</a></div></div>');
        } 
        $('#dataConfirmModal').find('.modal-body').text($(this).attr('data-confirm'));
        $('#dataConfirmOK').attr('href', href);
        $('#dataConfirmModal').modal({show:true});
        return false;
    });
});
</script>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary" onclick="javascript:window.location =''">Save changes</button>
  </div>
</div>

	<div class="container">
		<a href="{% url 'menu/add' %}"><button class="btn btn-primary" >增加菜品</button></a>
		</br>
		</br>

		<div class="btn-group">
			<button class="btn {%if not selected_category %}btn-primary{%endif%}" onclick="window.location.href='{% url 'menu/list' %}';">所有菜品</button>
			{%for category_id, category_name in menu_item_category_choices %}
  			<button class="btn {%if category_id == selected_category %}btn-primary{%endif%}" onclick="window.location.href='{% url 'menu/list' %}?category={{category_id}}';" >{{category_name}}</button>
  			{% endfor %}
		</div>
		</br>	
		</br>	
		<table class="table table-striped">
			<tr>
				<th>图片</th>
				<th>标题</th>
				<th>价格</th>
				<th>类别</th>
				<th>序号</th>
				<th>操作</th>
			</tr>
			{% for item in object_list%}
			<tr>
				<td><a href="{{STATIC_URL}}/menu/{{item.image_uri}}"><img src="{{STATIC_URL}}/menu/{{item.image_uri}}" class="img-roundeds" width="100" heigth="100" /></a></td>
				<td>{{item.title}}</td>
				<td>{{item.price}}</td>
				<td>{{item.get_category_display}}</td>
				<td>{{item.sorted_seq}}</td>
				<td>
					<!-- 
					<a href="{% url 'menu/update' item.menu_item_id %}"><button class="btn btn-success">修改</button></a></br></br>
					<a href="{% url 'menu/delete' item.menu_item_id %}" data-confirm="你确定要删除吗?"><button class="btn btn-danger" onclick="javascript:$('.alert').alert()" >删除</button></a></br>
					-->
					<div class="btn-group">
					  <a class="btn dropdown-toggle btn-primary" data-toggle="dropdown" href="#">
					   	操作 
					    <span class="caret"></span>
					  </a>
					  <ul class="dropdown-menu">
					  	<li><a href="{%url 'menu/update' item.menu_item_id %}">查看/修改</a></li>
						<li><a href="{%url 'menu/delete' item.menu_item_id %}" data-confirm="你确定要删除吗?" onclick="javascript:$('.alert').alert()">删除</a></li>
					  </ul>
					</div>				
				</td>
			</tr>
			{% endfor %}
		</table>
	</div>

{% endblock %}

xingyunbe/xingyun/templates/order_list.html
{% extends "layout.html" %}

{% block nav_order_class %}active{%endblock%}

{% block content %}
<script type="text/javascript">
$(document).ready(function() {
    $('a[data-confirm]').click(function(ev) {
        var href = $(this).attr('href');

        if (!$('#dataConfirmModal').length) {
            $('body').append('<div id="dataConfirmModal" class="modal" role="dialog" aria-labelledby="dataConfirmLabel" aria-hidden="true"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="dataConfirmLabel">确认删除</h3></div><div class="modal-body"></div><div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button><a class="btn btn-primary" id="dataConfirmOK">OK</a></div></div>');
        } 
        $('#dataConfirmModal').find('.modal-body').text($(this).attr('data-confirm'));
        $('#dataConfirmOK').attr('href', href);
        $('#dataConfirmModal').modal({show:true});
        return false;
    });
});
</script>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary" onclick="javascript:window.location =''">Save changes</button>
  </div>
</div>

	<div class="container">
		<div class="btn-group">
			<button class="btn {%if not selected_status %}btn-primary{%endif%}" onclick="window.location.href='{% url 'order/list' %}';">所有订单</button>
			{%for status_id, status_name in order_status_choices %}
  			<button class="btn {%if status_id == selected_status %}btn-primary{%endif%}" onclick="window.location.href='{% url 'order/list' %}?status={{status_id}}';">{{status_name}}</button>
  			{% endfor %}
		</div>
		</br>
		</br>
		<table class="table table-striped">
			<tr>
				<th>顾客姓名</th>
				<th>顾客联系电话</th>
				<th>用餐人数</th>
				<th>数量</th>
				<th>是否包厢</th>
				<th>就餐时间</th>
				<th>下单时间</th>
				<th>订单状态</th>
				<th>操作</th>
			</tr>
			{% for order in object_list%}
			<tr>
				<td>{{order.contact_name}}</td>
				<td>{{order.contact_phone}}</td>
				<td>{{order.people_number}}</td>
				<td>{{order.dishes_count}}</td>
				<td>{{order.get_box_required_display}}</td>
				<td>{{order.reserved_time|date:"Y-m-d H:i"}}</td>
				<td>{{order.order_creation_time|date:"Y-m-d H:i"}}</td>
				<td>{{order.get_order_status_display}}</td>
				<td>
				<!--  
					<a href=""><button class="btn btn-success">修改</button></a></br></br>
					<a href="" data-confirm="你确定要删除吗?"><button class="btn btn-danger" onclick="javascript:$('.alert').alert()" >删除</button></a></br>
				-->
					<div class="btn-group">
					  <a class="btn dropdown-toggle btn-primary" data-toggle="dropdown" href="#">
					   	操作 
					    <span class="caret"></span>
					  </a>
					  <ul class="dropdown-menu">
					  	<li><a href="{%url 'order/update' order.order_id %}">查看/修改</a></li>
						<li><a href="{%url 'order/delete' order.order_id %}" data-confirm="你确定要删除吗?" onclick="javascript:$('.alert').alert()">删除</a></li>
					  </ul>
					</div>
				</td>
			</tr>
			{% endfor %}
		</table>
	</div>

{% endblock %}